# 应用名称
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456

logging:
  level:
    root: info
    com.yz.blog: debug
  file:
    path: log/blog-dev.log


